global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ml_service'
    static_configs:
      - targets: ['ml_service:8001']
    metrics_path: '/metrics'
    
  - job_name: 'alert_service'  
    static_configs:
      - targets: ['alert_service:8002']
